### ISSUE TITLE
Sticking in Cache

### ISSUE THREAD

**Issue by galenseilis** [galenseilis/Mjolnir#2]
When I open the docs in a private browser session I see the current state of the docs:

![image](https://github.com/galenseilis/Mjolnir/assets/11385121/455bcfa2-5f6b-4691-b018-58ad30bd641a)

But when I am looking at the docs logged into my browser I see only a previous state.

![image](https://github.com/galenseilis/Mjolnir/assets/11385121/c1d9bbab-b9b2-47cc-894e-e616bd0ebe4f)

**Comment by galenseilis** [comment]
In `.github/workflows/ci.yml` I see that there is some reference to cache:

```yaml
name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocstrings 
      - run: mkdocs gh-deploy --force
   ```

It might be worth looking into that further.
